export type Language = "nl" | "en";
export type LanguageContent = {
  projectsHeader: string;
  aboutHeader: string;
  educationHeader: string;
  educationDegree: string;
  educationSchool: string;
  educationDescription: string;
  experienceHeader: string;
  odidoInternTitle: string;
  odidoInternDuration: string;
  odidoInternExperienceDescription: string;
  odidoParttimeTitle: string;
  odidoParttimeDuration: string;
  odidoParttimeExperienceDescription: string;
  experienceAhTitle: string;
  experienceAhPeriod: string;
  experienceAhDescription: string;
  certificationsHeader: string;
  certificationReactTitle: string;
  certificationReactDescription: string;
  certificationSwiftTitle: string;
  certificationSwiftDescription: string;
  certificationFlutterTitle: string;
  certificationFlutterDescription: string;
  hobbiesHeader: string;
  hobbyPowerlifting: string;
  hobbyDnD: string;
  hobbyGaming: string;
  powerliftingCalendarTitle: string;
  powerliftingCalendarDescription: string;
  drawSomethingTitle: string;
  drawSomethingDescription: string;
  portfolioTitle: string;
  portfolioDescription: string;
};
